weapons:
  AK-47:
    cooldown: 40  # 1 = 5 Ticks | 20 Ticks = 1 Second
  Type95:
    cooldown: 20
  Hunting:
    cooldown: 28
  Olympia:
    cooldown: 8
deny-message: "&cThis weapon is in cooldown for %cooldown% seconds."