name: MortisSwitchCooldown
version: '1.0'
main: me.none030.mortisswitchcooldown.MortisSwitchCooldown
api-version: 1.13
softdepend:
  - CrackShot
  - WeaponMechanics
  - QualityArmory
commands:
  cooldown:
    aliases:
      - mortiscooldown
      - switchcooldown
      - weaponswitchcooldown
